uploads = []
outputs = []

[[generated]]
id = "UgDXb7A4trA8wZOsCRTTn"
uri = "file://artifacts/poke-haven/public/hero-bowl.png"
type = "image"
title = "Hero poke bowl"

[[generated]]
id = "LCn9nEOdXAFS8-tfXS__7"
uri = "file://artifacts/poke-haven/public/classic-hawaiian.png"
type = "image"
title = "Classic Hawaiian bowl"

[[generated]]
id = "ExHLL0Gt03HoWoRNOn9Rs"
uri = "file://artifacts/poke-haven/public/spicy-tuna.png"
type = "image"
title = "Spicy Tuna bowl"

[[generated]]
id = "eXhZprvHU9msnj744ryF9"
uri = "file://artifacts/poke-haven/public/dragon-bowl.png"
type = "image"
title = "Dragon Bowl"

[[generated]]
id = "FmlKz2majg7ZQ43hga4_h"
uri = "file://artifacts/poke-haven/public/green-goddess.png"
type = "image"
title = "Green Goddess bowl"

[[generated]]
id = "QlnHtl36zVuM7COnrL8qF"
uri = "file://artifacts/poke-haven/public/sunset-bowl.png"
type = "image"
title = "Sunset Bowl"

[[generated]]
id = "CvjcFLmLyYyQRZC7icyIa"
uri = "file://artifacts/poke-haven/public/island-mango.png"
type = "image"
title = "Island Mango bowl"
